development:
  adapter: postgresql
  username:
  password: 
  database: verasay_dev

test:
  adapter: postgresql
  username:
  password:
  database: verasay_test
  min_messages:

production:
  adapter: postgresql
  username: 
  password:
  database: verasay_production